name: "Diag workflow_dispatch"

on:
  workflow_dispatch:

jobs:
  diag:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello! branch=${{ github.ref }} run_id=${{ github.run_id }}"
      - run: |
          echo "## Dispatch OK" >> $GITHUB_STEP_SUMMARY
          echo "Triggered by: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
